name: hitesh job 
#trigger point
on:
  push: 
     branches: ["dryrun-aws"]
     paths-ignore:
          - "README.md"
          - "terraform.tfstate"

#jobscreating jobs
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps: # what exactly you want to run in ubuntu machine
    - name: my first step to run
      run: |
        echo "Hello world"
        git version
        whomami
        ls -a


   

