name: hitesh job 
#trigger point
on:
  push: 
     branches: ["main"]
     paths-ignore:
          - "README.md"
          - "terraform.tfstate"

#jobscreating jobs
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps: # what exactly you want to run in ubuntu machine
       #calling first github action to clone my dryrun-aws data to runner machine
    - name: taking code from repo
      uses: actions/checkout@v5
      with:
        ref: main

       # terraform installing
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3

    - name: my first step to run
      run: |
        echo "Hello world"
        git version
        whoami
        ls -a
        

